### ISSUE TITLE
Case classes with a common `.toXml` method

### ISSUE THREAD

**Issue by abbggg** [jvican/xmlrpc#1]
Hello @jvican! Your library is very helpful for me, thanks.
I try to create a set of case classes to create XMLRPC requests with a common `.toXml` method.
Please look at the following code snippet:

```
import xmlrpc.protocol.Datatype
import xmlrpc.protocol.XmlrpcProtocol._

import scala.xml.NodeSeq

trait XmlRpcRequest extends Datatype[this.type] {
  protected def methodName: String
  def toXml: NodeSeq = writeXmlRequest[XmlRpcRequest](methodName, this)
}

case class StatRequest() extends XmlRpcRequest {
  override val methodName = "get_stat"
}
```

It has the compilation error:

```
/.../origin/xmlrpc/XmlRpcRequest.scala:16: could not find implicit value for evidence parameter of type xmlrpc.protocol.Datatype[StatRequest.this.type]
[error]   def toXml: NodeSeq = writeXmlRequest(methodName, this)
```

What `Datatype[T]` should I extend to override a serialize/deserialize methods implicitly?

**Comment by jvican** [comment]
Hi @vinograt, I feel ashamed. I had a problem with my mobile phone and it didn't send correctly my reply. I have realised the error right now.
So, as far as I know about your problem, you want to represent `XmlrpcRequest`, but this is not necessary with my module. In fact, it is much simpler. You just need to create something like this:

``` scala
val invocation = invokeMethod[Int, String]("examples.getStateName", 41)
```

Here you see that `invokeMethod` gets the name of the method to be called in the server and the input data (`41`). The function also needs two types (you have to write them explicitly): the first one is the input of the method (`Int`), and the second one is the type of the output (`String`). By the way, `invokeMethod` returns a Future, see more details [here](https://github.com/jvican/xmlrpc/blob/master/src/test/scala/xmlrpc/XmlrpcConnection.scala#L31-L38).

Automatically, my `xmlrpc` module will try to deserialize the response as a `String`. If it can't, you will get the corresponding error message.

I hope I have helped you and sorry for the delay.
