### ISSUE TITLE
How to work with Wordpress XML-RPC

### ISSUE THREAD

**Issue by nhandl3** [jvican/xmlrpc#2]
Hello Jorge @jvican, I am trying to use your library to work with Wordpress's xmlrpc, method https://codex.wordpress.org/XML-RPC_WordPress_API/Comments#wp.getCommentCount

I defined two case classes for request and reply:

``` scala
case class WpGetCommentCount(blog_id: Int, username: String, password: String, post_id: Int)
case class WpGetCommentCountReply(approved: Int, awaiting_moderation: Int, spam: Int, total_comments: Int)
```

Then invoke with:

``` scala
val invocation = invokeMethod[WpGetCommentCount, WpGetCommentCountReply]("wp.getCommentCount", WpGetCommentCount(blog_id = 1, username = "admin", password = """password""", post_id = 1)).underlying
```

The request was sent correctly and Wordpress replied but library could not parse response to WpGetCommentCountReply

```
Errors when deserializing
NonEmptyList(DeserializationError(This is an unexpected error. It may be because the type of response is not the specified,Some(java.util.NoSuchElementException: next on empty iterator)))
```

I also tried to make a raw request without Scala and Wordpress replied with raw XML:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <params>
    <param>
      <value>
      <struct>
  <member><name>approved</name><value><string>1</string></value></member>
  <member><name>awaiting_moderation</name><value><int>0</int></value></member>
  <member><name>spam</name><value><int>0</int></value></member>
  <member><name>total_comments</name><value><int>1</int></value></member>
      </struct>
      </value>
    </param>
  </params>
</methodResponse>
```

Should I modify something to make the parsing works correctly?

**Comment by jvican** [comment]
Hi there! The problem is that you receive a `struct`. This type is like a dictionary, so you should catch it with Map. However, my xmlrpc module is not able to infer types from collections (structs and arrays) of values with different types. In your example, your `struct` has both `int` and `string`. This leads to Map[String, Any].

This downside is specified in the _README_. If you want to make this functionality available, any PR is welcome. If not, I will try to do it when I have time.

**Comment by nhandl3** [comment]
Oh you are correct, it is a `struct`. Type inference ability would be a great strike, though I am a newbie to Scala so I definitely looking for your update :smile: 

Could I have a walk-through for this limitation such as get raw XML response then iterate through elements by myself? Thank you very much

**Comment by jvican** [comment]
There is not such a method.
However, use [this](https://github.com/jvican/xmlrpc/blob/master/src/main/scala/xmlrpc/Xmlrpc.scala#L41-L52) as a source of inspiration, it is dead easy to do a raw response with Spray.
