### ISSUE TITLE
Release for scalaz 7.2 and akka-http 10?

### ISSUE THREAD

**Issue by derekmorr** [jvican/xmlrpc#5]
It would help me if you could publish a release against scalaz 7.2 and using Akka HTTP 10, against both scala 2.11 and 2.12.

Thanks.

**Comment by jvican** [comment]
Fixed via https://github.com/jvican/xmlrpc/pull/6.

**Comment by derekmorr** [comment]
Can we get a 1.2 release published to SonaType?

**Comment by jvican** [comment]
Yes, just did it :smile:.

**Comment by derekmorr** [comment]
Sorry to be a pain - the published version is 1.2-SNAPSHOT. Are there additional changes pending for 1.2, or can we get a final 1.2 build published? I just don't liked depending on -SNAPSHOT versions in my projects.

**Comment by jvican** [comment]
Hey @derekmorr, I did publish 1.2 as well but it's not out there yet. If you don't get it in a few hours, please let me know and I'll look into it.

**Comment by derekmorr** [comment]
I don't see any 1.2 releases on Maven Central yet - https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.jvican%22%20AND%20a%3A%22xmlrpc_2.11%22

On SonaType I only see the 1.2-SNAPSHOT https://oss.sonatype.org/#nexus-search;quick~com.github.jvican.

**Comment by jvican** [comment]
Okay, I forgot to close the transaction, will do as soon as I get home! @derekmorr

**Comment by derekmorr** [comment]
Thanks!

**Comment by jvican** [comment]
Just landed in Maven Central: http://search.maven.org/#search|ga|1|jvican%20xmlrpc Let me know if something's wrong. Cheers to you!

**Comment by derekmorr** [comment]
Looks good on my end. Thanks!
