### ISSUE TITLE
upgrade Akka HTTP to fix security issue

### ISSUE THREAD

**Issue by derekmorr** [jvican/xmlrpc#7]
The akka team has released a security update to Akka HTTP - 10.0.2. We should update the project to require this version.

See http://akka.io/news/2017/01/23/akka-http-10.0.2-security-fix-released.html

**Comment by jvican** [comment]
Thanks for reporting! I'll be releasing a minor version tomorrow. By the way, I'm happy to give you merge rights if you want them.

**Comment by jvican** [comment]
Hey @derekmorr, I've just published 2.12.1, you can already depend on it.

**Comment by derekmorr** [comment]
Great. Thanks!

**Comment by derekmorr** [comment]
I assume you mean 1.2.1? Could you also publish a build for Scala 2.11?

Also, it might be good to update the README to refer to the new version.

**Comment by jvican** [comment]
Just published and updated README, and yes, 1.2.1!
